services:
  docker-version-fetcher:
    image: ghcr.io/th0mas2118/docker_version_fetcher:${IMAGE_VERSION:-latest}
    container_name: docker-version-checker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH:-/root/docker_fetcher_data}:/app/data
      - ./patches:/app/patches
      - ./entrypoint.sh:/app/entrypoint.sh
    environment:
      - GOTIFY_URL=${GOTIFY_URL}
      - GOTIFY_TOKEN=${GOTIFY_TOKEN}
      - GOTIFY_PRIORITY=${GOTIFY_PRIORITY:-5}
      - GOTIFY_TITLE=${GOTIFY_TITLE:-Docker Version Fetcher}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-86400}
      - NOTIFICATION_FREQUENCY=${NOTIFICATION_FREQUENCY:-7}
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]
    command: python run_periodic.py --daemon
