services:
  docker-version-fetcher:
    build: .
    container_name: docker-version-checker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      - GOTIFY_URL=${GOTIFY_URL}
      - GOTIFY_TOKEN=${GOTIFY_TOKEN}
      - GOTIFY_PRIORITY=${GOTIFY_PRIORITY:-5}
      - GOTIFY_TITLE=${GOTIFY_TITLE:-Docker Version Fetcher}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-86400}
      - NOTIFICATION_FREQUENCY=${NOTIFICATION_FREQUENCY:-7}
    restart: unless-stopped
    command: python run_periodic.py --daemon
