name: Build and Push Docker Image

# Définit quand ce workflow sera déclenché
on:
  push:
    tags:
      - '*'  # Se déclenche pour tous les tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu pour exécuter les tâches
    
    steps:
      # Étape 1: Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Étape 2: Configurer Docker Buildx (pour les builds multi-plateformes)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Étape 3: Se connecter à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4: Extraire les métadonnées (comme le numéro de version du tag)
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/docker_version_fetcher
          tags: |
            type=ref,event=tag
            type=raw,value=latest
      
      # Étape 5: Construire et pousser l'image Docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

